package sistemafarmacia.presentacion;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import sistemafarmacia.Fondo;
import sistemafarmacia.VariablesFunciones;
import sistemafarmacia.entidades.Usuario;

public class FrmPrincipal extends javax.swing.JFrame {
    private static final String TITLE = "Principal";
    VariablesFunciones variables = new VariablesFunciones();
    private static Usuario usuarioSession;

    public static Usuario getUsuarioSession() {
        return usuarioSession;
    }
    public FrmPrincipal(Usuario usuario) {
        initComponents();
        
        this.setTitle(variables.getTitle()+TITLE);
        this.setLocationRelativeTo(null);     
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setIconImage(variables.getIconoVentana());
        pnlBanner.setBackground(variables.getColor());
        pnlPie.setBackground(variables.getColor());
       
        btnClientes.setIcon(variables.getIconoBoton(btnClientes, 90, 10, "cliente"));
        btnProducto.setIcon(variables.getIconoBoton(btnProducto, 100, 10, "producto"));
        btnGenVenta.setIcon(variables.getIconoBoton(btnGenVenta, 130, 10, "venta"));
              
        this.add(new Fondo(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height), BorderLayout.CENTER);
        usuarioSession = usuario;        
        lblNombreUsuario.setText(usuario.getPersona().getNombres()+" "+usuario.getPersona().getApellidos());
        lblPrivilegio.setText(usuario.getPerfil());
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblPrivilegio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlBanner = new javax.swing.JPanel();
        btnGenVenta = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenu();
        mnuProducto = new javax.swing.JMenuItem();
        mnuLaboratorio = new javax.swing.JMenuItem();
        mnuTipoProducto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuListaVentas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuRegistrarVenta = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre Completo de Usuario");

        lblPrivilegio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrivilegio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrivilegio.setText("Administrador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Privilegio:");

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblPrivilegio))
                    .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblNombreUsuario)))
                .addContainerGap())
        );

        btnGenVenta.setText("Generar Venta");
        btnGenVenta.setFocusable(false);
        btnGenVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGenVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenVentaActionPerformed(evt);
            }
        });

        btnProducto.setText("Productos");
        btnProducto.setFocusable(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuAdministracion.setText("Administración");

        mnuProducto.setText("Productos");
        mnuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductoActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuProducto);

        mnuLaboratorio.setText("Laboratorio");
        mnuLaboratorio.setToolTipText("");
        mnuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaboratorioActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuLaboratorio);

        mnuTipoProducto.setText("Tipo Producto");
        mnuTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoProductoActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuTipoProducto);
        mnuAdministracion.add(jSeparator1);

        mnuListaVentas.setText("Lista de ventas");
        mnuListaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaVentasActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuListaVentas);

        jMenuBar1.add(mnuAdministracion);

        jMenu2.setText("Ventas");

        mnuRegistrarVenta.setText("Generar Venta");
        mnuRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuRegistrarVenta);

        mnuCliente.setText("Clientes");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCliente);

        jMenuBar1.add(jMenu2);

        mnuAyuda.setText("Ayuda");

        mnuAcerca.setText("Acerca de ...");
        mnuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcerca);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(pnlPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenVentaActionPerformed
        DlgGenerarVenta generarVenta= new DlgGenerarVenta(this, rootPaneCheckingEnabled);
        generarVenta.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnGenVentaActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        DlgProducto producto= new DlgProducto(this, rootPaneCheckingEnabled);
        producto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaboratorioActionPerformed
        DlgLaboratorio laboratorio= new DlgLaboratorio(this, rootPaneCheckingEnabled,0);
        laboratorio.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuLaboratorioActionPerformed

    private void mnuTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoProductoActionPerformed
        DlgProductoTipo tipoProducto= new DlgProductoTipo(this, rootPaneCheckingEnabled,0);
        tipoProducto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuTipoProductoActionPerformed

    private void mnuRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarVentaActionPerformed
        DlgGenerarVenta generarVenta= new DlgGenerarVenta(this, rootPaneCheckingEnabled);
        generarVenta.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuRegistrarVentaActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        DlgCliente cliente= new DlgCliente(this, rootPaneCheckingEnabled);
        cliente.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        DlgCliente cliente= new DlgCliente(this, rootPaneCheckingEnabled);
        cliente.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void mnuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductoActionPerformed
        DlgProducto producto= new DlgProducto(this, rootPaneCheckingEnabled);
        producto.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuProductoActionPerformed

    private void mnuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaActionPerformed
        DlgAcerca acerca = new DlgAcerca(this, rootPaneCheckingEnabled);
        acerca.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuAcercaActionPerformed

    private void mnuListaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaVentasActionPerformed
        DlgListaVenta listaVenta = new DlgListaVenta(this, rootPaneCheckingEnabled);
        listaVenta.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuListaVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal(usuarioSession).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGenVenta;
    public javax.swing.JButton btnProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPrivilegio;
    private javax.swing.JMenuItem mnuAcerca;
    public javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuLaboratorio;
    private javax.swing.JMenuItem mnuListaVentas;
    private javax.swing.JMenuItem mnuProducto;
    private javax.swing.JMenuItem mnuRegistrarVenta;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTipoProducto;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlPie;
    // End of variables declaration//GEN-END:variables
}
